# LDTGaffer
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export LDTGAFFER=$SCRIPT_DIR
export GAFFERUI_IMAGE_PATHS=$GAFFERUI_IMAGE_PATHS:$LDTGAFFER
export GAFFER_REFERENCE_PATHS=$GAFFER_REFERENCE_PATHS:$LDTGAFFER/resources/boxes
export PYTHONPATH=$PYTHONPATH:$LDTGAFFER/python
export GAFFER_STARTUP_PATHS=$GAFFER_STARTUP_PATHS:$LDTGAFFER/startup
export GAFFER_EXTENSION_PATHS=$GAFFER_EXTENSION_PATHS$(find $LDTGAFFER/extensions -maxdepth 1 -type d -printf ":%p")
export OSL_SHADER_PATHS=$OSL_SHADER_PATHS:$LDTGAFFER/osl

exe() { echo "\$ ${@/eval/}" ; "$@" ; }

# ECHO GAFFER PATHS FOR INSPECTION
exe eval "export |grep GAFFER"